### ISSUE TITLE
Refresh contents in queue upon adding a new song

### ISSUE THREAD

**Issue by ZachPole** [dhs43/QueueHub#4]
Adding a song refreshes the queue and adds the new song to the top. Due to how we organize the "queue" on FireBase, sometimes the order is off.

**Comment by acarteas** [comment]
How was this resolved?

**Comment by ZachPole** [comment]
When adding a new song, the function that obtains the recycler view is called again, after the song is uploaded, and retrieves all of the songs in the database once more.
